
  version: '3.8'
  services:
    postgres-db:
      image: dockerhub.timeweb.cloud/library/postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "5433:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data
      restart: unless-stopped

    spring-app:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      depends_on:
        - postgres-db
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/postgres
      restart: unless-stopped

  volumes:
    pgdata:
